### ISSUE TITLE
Use /usuario instead of /usuario/status

### ISSUE THREAD

**Issue by matheusgr** [felipemarinho97/RUVaiAbrir#4]
https://github.com/felipemarinho97/RUVaiAbrir/blob/2b6c13644da14bfdd2360c64c2a08acc6f253a1e/backend/src/main/java/ml/darklyn/RUVaiAbrir/status/StatusController.java#L46

Why not use the usuario resource to represent its status? That or call it a /usuario_status.

Usually a /usuario/1/status means a resource inside of another resource... so the /usuario/status is a little strange path.

**Comment by felipemarinho97** [comment]
yes, _/usuario/status_ is really strange, /usuario-status is a better choice
